In [6]:
from statistics import linear_regression

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import root_mean_squared_error

In [7]:
data = pd.read_csv(r"../regressao/train.csv")
# test_data = pd.read_csv(r"C:\Users\marce\PycharmProjects\ufrj-analytica-training\entregaveis\machine_learning\regressao\test.csv")

In [8]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,score
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,5.67
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,5.33
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,8.33
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,14.67
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,8.67

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  score       395 non-null    float64
dtypes: float64(1), int64(13), str(17)
memory usage: 116.5 KB

In [10]:
data.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,score
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.679139
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.696912
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.330000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.330000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,10.670000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.330000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.330000

In [11]:
data.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
score         0
dtype: int64

Separar os dados em features (X) e target (Y). Depois, separar em train and test utilizando a função train_test_split.

In [12]:
X = data.drop(columns=["score"])
y = data[["score"]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Em primeiro lugar, precisamos realizar o pré-processamento dos dados. As colunas categóricas vão ser codificadas com One-Hot Encoding, e as colunas numéricas vão ser normalizadas para uma distribuição gaussiana de média zero e variância unitária, a partir do uso da classe StandardScaler().

In [13]:
categorical = ["school", "sex", "address", "famsize", "Pstatus", "Medu", "Fedu", "Mjob", "Fjob", "reason", "guardian", "schoolsup", "famsup", "paid", "activities", "nursery", "higher", "internet", "romantic"]
numerical = ["age", "absences"]

In [14]:
ohe = OneHotEncoder(handle_unknown="ignore", drop="if_binary")
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", ohe, categorical),
        ("num", StandardScaler(), numerical),
    ]
)

Vamos utilizar dois modelos: Regressão Linear e Regressão Linear Regularizada Ridge, e fazer a comparação do erro gerado por cada um. Abaixo, o pipeline realiza o pré-processamento e treina o respectivo modelo.

In [21]:
linear_regression_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression()),
])

ridge_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", Ridge()),
])

In [22]:
linear_regression_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='if_binary',
                                                                handle_unknown='ignore'),
                                                  ['school', 'sex', 'address',
                                                   'famsize', 'Pstatus', 'Medu',
                                                   'Fedu', 'Mjob', 'Fjob',
                                                   'reason', 'guardian',
                                                   'schoolsup', 'famsup',
                                                   'paid', 'activities',
                                                   'nursery', 'higher',
                                                   'internet', 'romantic']),
                                                 ('num', StandardScaler(),
                                                  ['age', 'absences'])])),
                ('regressor', LinearRegression())])

In [23]:
ridge_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='if_binary',
                                                                handle_unknown='ignore'),
                                                  ['school', 'sex', 'address',
                                                   'famsize', 'Pstatus', 'Medu',
                                                   'Fedu', 'Mjob', 'Fjob',
                                                   'reason', 'guardian',
                                                   'schoolsup', 'famsup',
                                                   'paid', 'activities',
                                                   'nursery', 'higher',
                                                   'internet', 'romantic']),
                                                 ('num', StandardScaler(),
                                                  ['age', 'absences'])])),
                ('regressor', Ridge())])

In [24]:
y_reg_pred = linear_regression_model.predict(X_test)
y_ridge_pred = ridge_model.predict(X_test)

Métrica de Avaliação - RMSE (Root Mean Squared Error)

In [19]:
rmse_regression = root_mean_squared_error(y_test, y_reg_pred)
rmse_regression

3.6381644424275934

In [20]:
rmse_ridge = root_mean_squared_error(y_test, y_ridge_pred)
rmse_ridge

3.5873463154365117

Acima, observamos que o modelo de regressão linear regularizado (Ridge) obteve um erro quadrático ligeiramente menor que o modelo de regressão linear padrão: 3.58 contra 3.63. Por isso, vamos utilizar o modelo Ridge para fazer testes sobre os dados do arquivo test.csv.

In [25]:
test_data_df = pd.read_csv("../regressao/test.csv")

In [27]:
data_prediction = ridge_model.predict(test_data_df)

In [29]:
data_prediction_df = pd.DataFrame(data_prediction)
data_prediction_df

            0
0   10.951449
1   11.075472
2    9.171771
3   12.330971
4    9.653550
5   11.247188
6   10.597071
7    9.179713
8    9.353625
9    8.137141
10   9.990405
11  10.537444
12  10.218843
13   8.172553
14  10.160725
15   9.437585
16  11.738828
17  11.354657
18  10.029722
19  10.457035
20  13.097872
21  12.126245
22  12.446169
23   9.906516
24  12.817602
25  10.886468
26   8.774971
27  11.301574
28  12.300812
29  11.771762
30  10.125114
31   9.851783
32   9.545463
33  10.052561
34   9.519137
35  10.510168
36  10.752748
37   8.808777
38   9.140261
39  10.441884

In [31]:
data_prediction_df.to_csv("../regressao/submission.csv")