# Atividade de vendas no Brasil

In [23]:
# imports
import numpy as np
import pandas as pd

## Entregável 1 NumPy

### A. Criando arrays

In [55]:
# windows
# dados = pd.read_csv(r'C:\Users\ateka\OneDrive\Documentos\GitHub\ufrj-analytica-training\data\vendas_brasil_1.csv')

# linux
dados = pd.read_csv('/home/tefxeb/Dev/Analytica/ufrj-analytica-training/data/vendas_brasil_1.csv')
dados

,data_venda,mes,cidade,canal_venda,categoria,produto,vendedor,fidelidade_cliente,preco_unitario,custo_unitario,...,quantidade,desconto_pct,receita_total,frete,avaliacao_cliente,prazo_entrega_dias,devolucao,entrega_no_prazo,alta_temporada,flag_outlier_preco
0,2022-04-13,4,Rio de Janeiro,App Mobile,Eletrônicos,Notebook,Bruno Souza,Diamante,739.39,561.75,...,10,5.2,6933.48,8.68,4.92,5.0,False,True,False,False
1,2023-03-12,3,Manaus,Site Web,Vestuário,Camiseta,Elisa Costa,Bronze,187.48,135.15,...,5,0.6,930.28,NaN,4.98,19.0,True,False,False,False
2,2022-09-28,9,Goiânia,App Mobile,Vestuário,Tênis,João Vieira,Bronze,76.11,61.40,...,14,0.7,1058.50,7.98,3.47,NaN,True,True,False,False
3,2022-04-17,4,Fortaleza,Site Web,Vestuário,Calça Jeans,Carla Mendes,Bronze,145.86,88.53,...,11,0.6,1592.43,20.49,4.50,16.0,False,True,False,False
4,2022-03-13,3,Belo Horizonte,App Mobile,Esportes,Bicicleta,João Vieira,Bronze,133.92,107.25,...,1,19.5,107.64,22.89,3.49,13.0,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37612,2023-12-31,3,Porto Alegre,App Mobile,Alimentação,Barra de Cereal,Gabi Alves,Bronze,73.11,47.38,...,9,20.3,524.49,8.15,4.95,NaN,False,False,False,False
37613,2023-12-31,9,Salvador,Site Web,Alimentação,Mel Orgânico,Henrique Dias,Bronze,76.62,55.50,...,12,10.7,820.52,41.74,4.49,19.0,False,False,False,False
37614,2023-12-31,2,Salvador,Loja Física,Alimentação,Whey Protein,Fábio Ramos,Bronze,55.15,36.94,...,7,0.0,384.44,85.35,4.02,14.0,False,True,False,False
37615,2023-12-31,11,São Paulo,Site Web,Esportes,Tapete de Yoga,João Vieira,Bronze,197.09,167.23,...,7,10.9,1960.18,30.99,3.50,6.0,False,True,True,False
37616,2023-12-31,4,Fortaleza,Televendas,Eletrônicos,Tablet,Inês Nunes,Prata,1057.41,870.69,...,4,10.0,3795.73,27.23,4.02,16.0,False,True,False,True

In [56]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 37617 entries, 0 to 37616
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   data_venda          37617 non-null  str
 1   mes                 37617 non-null  int64
 2   cidade              37617 non-null  str
 3   canal_venda         37567 non-null  str
 4   categoria           37617 non-null  str
 5   produto             37617 non-null  str
 6   vendedor            37577 non-null  str
 7   fidelidade_cliente  37617 non-null  str
 8   preco_unitario      37617 non-null  float64
 9   custo_unitario      37617 non-null  float64
 10  margem_pct          37535 non-null  float64
 11  quantidade          37617 non-null  int64
 12  desconto_pct        37617 non-null  float64
 13  receita_total       37617 non-null  float64
 14  frete               35738 non-null  float64
 15  avaliacao_cliente   34662 non-null  float64
 16  prazo_entrega_dias  36113 non-null  float64
 17  devolucao           37617 non-null  bool
 18  entrega_no_prazo    37617 non-null  bool
 19  alta_temporada      37617 non-null  bool
 20  flag_outlier_preco  37617 non-null  bool
dtypes: bool(4), float64(8), int64(2), str(7)
memory usage: 5.0 MB

In [57]:
dados.isnull().sum()

data_venda               0
mes                      0
cidade                   0
canal_venda             50
categoria                0
produto                  0
vendedor                40
fidelidade_cliente       0
preco_unitario           0
custo_unitario           0
margem_pct              82
quantidade               0
desconto_pct             0
receita_total            0
frete                 1879
avaliacao_cliente     2955
prazo_entrega_dias    1504
devolucao                0
entrega_no_prazo         0
alta_temporada           0
flag_outlier_preco       0
dtype: int64

In [58]:
dados["avaliacao_cliente"].unique()

array([4.92, 4.98, 3.47, 4.5 , 3.49, 2.99, 1.99, 3.03, 4.46, 4.01, 3.97,
       4.52, 1.01, 4.51, 3.53, 3.52, 3.55, 2.94,  nan, 4.47, 1.05, 5.  ,
       3.99, 4.49, 4.  , 3.04, 3.  , 4.03, 4.96, 4.06, 3.96, 3.93, 1.95,
       4.53, 2.01, 4.02, 3.5 , 4.97, 3.98, 3.43, 3.02, 3.46, 2.98, 4.99,
       4.45, 3.01, 3.07, 3.54, 4.04, 4.44, 3.51, 2.02, 4.48, 1.97, 4.05,
       2.96, 4.56, 4.43, 3.57, 4.55, 3.56, 2.04, 1.91, 4.08, 3.45, 3.48,
       3.06, 1.93, 3.05, 4.07, 1.98, 1.03, 4.54, 1.07, 2.  , 4.95, 1.02,
       3.95, 1.04, 2.06, 3.44, 1.06, 4.94, 1.  , 2.91, 3.08, 4.41, 3.91,
       3.4 , 4.93, 2.97, 3.94, 4.91, 3.6 , 4.09, 2.92, 4.89, 4.59, 1.96,
       2.95, 2.05, 2.93, 2.03, 2.88, 2.08, 4.58, 4.57, 4.61, 4.6 , 3.09,
       4.11, 4.62, 3.88, 4.4 , 3.42, 3.92, 3.87, 2.89, 3.58, 3.39, 4.42,
       1.94, 2.1 , 1.09, 2.07, 3.13, 3.1 , 1.9 , 4.9 , 2.87, 4.88, 4.39,
       3.59, 3.9 , 3.89, 3.12, 3.11, 3.41, 1.08, 1.89, 4.1 , 4.12, 1.88,
       2.09, 3.38, 4.35, 3.84, 3.37, 2.9 , 1.11, 1.92, 2.11, 4.37, 4.38,
       1.1 , 4.13, 4.86, 4.65, 4.63, 3.62, 4.15, 3.61, 1.12, 3.86, 2.14,
       4.87, 4.36, 4.64, 3.64, 1.85, 2.86, 3.36, 3.63, 1.15])

In [27]:
# criando arrays numpy a partir de algumas colunas numéricas do DataFrame
# substituindo valores nulos por 0 por questões de consistência de cálculo!

# preço unitário
preco_unitario = dados['preco_unitario'].fillna(0).to_numpy()
print("Preço unitário:", preco_unitario)

# custo unitário
custo_unitario = dados['custo_unitario'].fillna(0).to_numpy()
print("Custo unitário:", custo_unitario)

# quantidade
quantidade = dados['quantidade'].fillna(0).to_numpy()
print("Quantidade:", quantidade)

# desconto
desconto = dados['desconto_pct'].fillna(0).to_numpy()
print("Desconto (%):", desconto)

# receita total
receita_total = dados['receita_total'].fillna(0).to_numpy()
print("Receita total:", receita_total)

# frete
frete = dados['frete'].fillna(0).to_numpy()
print("Frete:", frete)

Preço unitário: [ 739.39  187.48   76.11 ...   55.15  197.09 1057.41]
Custo unitário: [561.75 135.15  61.4  ...  36.94 167.23 870.69]
Quantidade: [10  5 14 ...  7  7  4]
Desconto (%): [ 5.2  0.6  0.7 ...  0.  10.9 10. ]
Receita total: [6933.48  930.28 1058.5  ...  384.44 1960.18 3795.73]
Frete: [ 8.68  0.    7.98 ... 85.35 30.99 27.23]

### B. Cálculos com operações vetorizadas

In [28]:
#1. valor bruto da venda
valor_bruto_venda = preco_unitario * quantidade
print("Valor bruto da venda:", valor_bruto_venda)

#2. valor do desconto
valor_desconto = valor_bruto_venda * desconto / 100
print("Valor do desconto:", valor_desconto)

#3. custo total
custo_total = custo_unitario * quantidade
print("Custo total:", custo_total)

#4. lucro estimado
lucro_estimado = valor_bruto_venda - (valor_desconto + custo_total + frete)
print("Lucro estimado:", lucro_estimado)

Valor bruto da venda: [7393.9   937.4  1065.54 ...  386.05 1379.63 4229.64]
Valor do desconto: [384.4828    5.6244    7.45878 ...   0.      150.37967 422.964  ]
Custo total: [5617.5   675.75  859.6  ...  258.58 1170.61 3482.76]
Lucro estimado: [1383.2372   256.0256   190.50122 ...   42.12      27.65033  296.686  ]

### C. Máscaras booleanas

In [29]:
#1. vendas com receita acima da média
mascara_receita_acima_media = receita_total > np.mean(receita_total)

#2. vendas com prejuízo
mascara_prejuizo = lucro_estimado < 0

#3. vendas com desconto alto
mascara_desconto_alto = desconto > 20

In [30]:
print(f'Quantidade de vendas com receita acima da média: {len(dados[mascara_receita_acima_media])} ({round((len(dados[mascara_receita_acima_media]['receita_total']) / len(dados)) * 100, 2)} %)')

print(f'Quantidade de vendas com desconto alto: {sum(mascara_desconto_alto)} ({round((sum(mascara_desconto_alto) / len(dados)) * 100, 2)} %)')

Quantidade de vendas com receita acima da média: 9236 (24.55 %)
Quantidade de vendas com desconto alto: 7037 (18.71 %)

### D. Agregações

In [31]:
#1. receita média
receita_media = np.mean(receita_total)
print("Receita média: R$", round(receita_media, 2))

#2. maior receita
maior_receita = np.max(receita_total)
print("Maior receita: R$", round(maior_receita, 2))

#3. menor receita
menor_receita = np.min(receita_total)
print("Menor receita: R$", round(menor_receita, 2))

#4. lucro médio
lucro_media = np.mean(lucro_estimado)
print("Lucro médio: R$", round(lucro_media, 2))

#5. quantidade de vendas com prejuízo
quantidade_prejuizo = sum(mascara_prejuizo)
print(f'Quantidade de vendas com prejuízo: {sum(mascara_prejuizo)} itens ({round((sum(mascara_prejuizo) / len(dados)) * 100, 2) } %)')

Receita média: R$ 1891.69
Maior receita: R$ 58430.28
Menor receita: R$ 3.7
Lucro médio: R$ 313.64
Quantidade de vendas com prejuízo: 7588 itens (20.17 %)

### Conclusão

Em geral,

## Entregável 2 Pandas

### A. Primeiro olhar no dataset

In [32]:
dados.describe()

,mes,preco_unitario,custo_unitario,margem_pct,quantidade,desconto_pct,receita_total,frete,avaliacao_cliente,prazo_entrega_dias
count,37617.000000,37617.000000,37617.000000,37535.000000,37617.000000,37617.000000,37617.000000,35738.000000,34662.000000,36113.000000
mean,6.517691,253.214933,183.620999,22.714776,7.481750,9.494048,1891.688173,29.885737,3.912094,10.017113
std,3.439296,316.742367,231.376757,8.670213,4.322273,9.097484,2972.445759,24.765161,0.932256,5.477487
min,1.000000,4.940000,3.010000,-0.570000,1.000000,0.000000,3.700000,3.750000,1.000000,1.000000
25%,4.000000,68.960000,49.550000,16.380000,4.000000,0.300000,364.280000,12.190000,3.490000,5.000000
50%,7.000000,111.300000,80.990000,22.700000,7.000000,9.000000,789.570000,22.250000,4.010000,10.000000
75%,9.000000,257.680000,186.570000,29.250000,11.000000,19.000000,1853.210000,39.480000,4.520000,15.000000
max,12.000000,9008.600000,6578.260000,44.270000,161.000000,26.000000,58430.280000,243.820000,5.000000,19.000000

In [33]:
print(f"1. Quantas linhas e colunas existem? R: {dados.shape[0]} linhas e {dados.shape[1]} colunas")

print(f"\n2. Existem dados faltantes? R: Sim! Tem {dados.isnull().sum().sum()} espaços com dados faltantes. Mais especificamente nas seguintes colunas:")
print(dados.isnull().sum())

print(f"\n3. Quais colunas parecem numéricas? R: As colunas que parecem numéricas são: {dados.select_dtypes(include=[np.number]).columns.tolist()}")

print(f"\n4. Quais colunas parecem categóricas? R: As colunas que parecem categóricas são: {dados.select_dtypes(include=[object]).columns.tolist()}")

1. Quantas linhas e colunas existem? R: 37617 linhas e 21 colunas

2. Existem dados faltantes? R: Sim! Tem 6510 espaços com dados faltantes. Mais especificamente nas seguintes colunas:
data_venda               0
mes                      0
cidade                   0
canal_venda             50
categoria                0
produto                  0
vendedor                40
fidelidade_cliente       0
preco_unitario           0
custo_unitario           0
margem_pct              82
quantidade               0
desconto_pct             0
receita_total            0
frete                 1879
avaliacao_cliente     2955
prazo_entrega_dias    1504
devolucao                0
entrega_no_prazo         0
alta_temporada           0
flag_outlier_preco       0
dtype: int64

3. Quais colunas parecem numéricas? R: As colunas que parecem numéricas são: ['mes', 'preco_unitario', 'custo_unitario', 'margem_pct', 'quantidade', 'desconto_pct', 'receita_total', 'frete', 'avaliacao_cliente', 'prazo_entrega_dias']

4. Quais colunas parecem categóricas? R: As colunas que parecem categóricas são: ['data_venda', 'cidade', 'canal_venda', 'categoria', 'produto', 'vendedor', 'fidelidade_cliente']

/tmp/ipykernel_3946/2036586506.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f"\n4. Quais colunas parecem categóricas? R: As colunas que parecem categóricas são: {dados.select_dtypes(include=[object]).columns.tolist()}")

### B. Limpeza e tratamento

In [54]:
# coluna de data para datetime

dados['data_venda'] = pd.to_datetime(dados['data_venda'], errors='coerce')
dados[dados['data_venda'].isnull() == True]

,data_venda,mes,cidade,canal_venda,categoria,produto,vendedor,fidelidade_cliente,preco_unitario,custo_unitario,...,quantidade,desconto_pct,receita_total,frete,avaliacao_cliente,prazo_entrega_dias,devolucao,entrega_no_prazo,alta_temporada,flag_outlier_preco
16,NaT,10,Rio de Janeiro,Marketplace,Livros,Álgebra Linear,Elisa Costa,Prata,56.93,48.29,...,9,0.0,515.25,17.63,3.55,16.0,False,True,False,False
207,NaT,9,Porto Alegre,Site Web,Eletrônicos,Smartwatch,Fábio Ramos,Bronze,671.41,555.95,...,14,20.8,7416.32,20.59,4.06,6.0,False,False,False,False
336,NaT,7,Goiânia,Televendas,Vestuário,Calça Jeans,João Vieira,Ouro,96.49,74.66,...,4,0.0,385.84,49.36,1.01,8.0,False,True,False,False
339,NaT,5,Belo Horizonte,Televendas,Livros,Estatística Aplicada,Elisa Costa,Diamante,105.79,70.48,...,12,5.1,1195.40,20.57,4.01,3.0,False,True,False,False
544,NaT,10,Rio de Janeiro,App Mobile,Livros,Estatística Aplicada,João Vieira,Ouro,42.27,29.70,...,1,25.8,31.20,16.36,2.94,16.0,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37144,NaT,3,Curitiba,Loja Física,Esportes,Tapete de Yoga,Gabi Alves,Bronze,127.84,99.10,...,5,0.8,628.53,25.89,5.00,7.0,True,True,False,False
37263,NaT,1,Belo Horizonte,App Mobile,Livros,Álgebra Linear,Carla Mendes,Bronze,50.90,34.16,...,4,5.1,297.10,56.46,2.93,18.0,False,True,True,False
37315,NaT,6,Porto Alegre,Site Web,Livros,Machine Learning,Diego Ferreira,Ouro,100.42,67.88,...,4,14.1,346.83,11.88,3.53,1.0,False,True,False,False
37333,NaT,6,Manaus,Site Web,Vestuário,Jaqueta,Gabi Alves,Bronze,123.12,103.71,...,5,0.0,612.70,30.15,3.03,2.0,True,True,False,False
37373,NaT,8,Rio de Janeiro,App Mobile,Vestuário,Tênis,Elisa Costa,Prata,62.19,52.59,...,7,19.9,348.42,18.56,NaN,14.0,False,True,False,False

Organizei algumas categorias das colunas categóricas que estavam com erros e troquei os valores nulos pela categoria "Não Informado"

In [35]:
dados["cidade"] = dados["cidade"].replace({
    "Rio de janeiro": "Rio de Janeiro", 
    "RJ": "Rio de Janeiro",
    "Rio de Janeiro ":"Rio de Janeiro",
    "Rio De Janeiro":"Rio de Janeiro",
    "Rio":"Rio de Janeiro",
    " Rio de Janeiro":"Rio de Janeiro",

    "B. Horizonte":"Belo Horizonte",
    "BH":"Belo Horizonte",
    "Belo horizonte":"Belo Horizonte",
    "Belo Horizonte ":"Belo Horizonte",
    " Belo Horizonte":"Belo Horizonte",

    " Salvador":"Salvador",
    "Slavador":"Salvador",
    "salvador":"Salvador",
    "Salvador ":"Salvador",

    " Fortaleza":"Fortaleza",
    "Fortaleza ":"Fortaleza",

    "Sao Paulo":"São Paulo",
    " São Paulo":"São Paulo",
    "São paulo":"São Paulo",
    "SP":"São Paulo",
    "S. Paulo":"São Paulo",
    "São Paulo ":"São Paulo",

    " Curitiba":"Curitiba",
    "Curtiba":"Curitiba",
    "curitiba":"Curitiba",
    "Curitiba ":"Curitiba",

    "Goiânia ":"Goiânia",
    " Goiânia":"Goiânia",

    " Manaus":"Manaus",
    "Manaus ":"Manaus",

    "Porto Alegre ":"Porto Alegre",
    " Porto Alegre":"Porto Alegre",

    "Recife ":"Recife",
    " Recife" :"Recife",
    })

dados["cidade"].unique()

<StringArray>
['Rio de Janeiro',         'Manaus',        'Goiânia',      'Fortaleza',
 'Belo Horizonte',         'Recife',      'São Paulo',   'Porto Alegre',
       'Salvador',       'Curitiba']
Length: 10, dtype: str

In [36]:
dados["fidelidade_cliente"] = dados["fidelidade_cliente"].replace({
    "ouro" :"Ouro",
    "OURO" :"Ouro",

    "prata" :"Prata",
    "PRATA" :"Prata",

    "bronze" :"Bronze",
    "BRONZE" :"Bronze",

    "diamante" :"Diamante",
    "DIAMANTE" :"Diamante",
})

dados["fidelidade_cliente"].unique()

<StringArray>
['Diamante', 'Bronze', 'Prata', 'Ouro']
Length: 4, dtype: str

In [37]:
dados["vendedor"] = dados["vendedor"].replace({
    "Bruno Souza " :"Bruno Souza",
    " Inês Nunes" :"Inês Nunes",
    " Ana Lima" :"Ana Lima",
    " Diego Ferreira" :"Diego Ferreira",
    " Fábio Ramos" :"Fábio Ramos",
    " Elisa Costa" :"Elisa Costa",
    " Carla Mendes" :"Carla Mendes",
    "Elisa Costa " :"Elisa Costa",
    " Bruno Souza" :"Bruno Souza",
    " João Vieira" :"João Vieira",
    "Ana Lima " :"Ana Lima",
    "João Vieira " :"João Vieira",
    "Inês Nunes " :"Inês Nunes",
    "Henrique Dias " :"Henrique Dias",
    " Henrique Dias": "Henrique Dias",
    "Carla Mendes " :"Carla Mendes",
    "Fábio Ramos " :"Fábio Ramos",
    "Gabi Alves " :"Gabi Alves",
    "Diego Ferreira " :"Diego Ferreira",
    " Gabi Alves" :"Gabi Alves",
})

dados["vendedor"] = dados["vendedor"].fillna('Não Informado')

dados["vendedor"].unique()

<StringArray>
[   'Bruno Souza',    'Elisa Costa',    'João Vieira',   'Carla Mendes',
  'Henrique Dias',     'Inês Nunes',       'Ana Lima',    'Fábio Ramos',
     'Gabi Alves', 'Diego Ferreira',  'Não Informado']
Length: 11, dtype: str

In [38]:
dados["canal_venda"] = dados["canal_venda"].replace({
    "APP Mobile" :"App Mobile",
    "App mobile" :"App Mobile",
    "app mobile" :"App Mobile",

    "site web" :"Site Web",
    "Site web" :"Site Web",
    "SiteWeb" :"Site Web",

    "Loja Fisica" :"Loja Física",
    "loja física" :"Loja Física",
    "Loja fisica" :"Loja Física",
})

dados["canal_venda"] = dados["canal_venda"].fillna('Não Informado')

dados["canal_venda"].unique()

<StringArray>
[   'App Mobile',      'Site Web',   'Loja Física',   'Marketplace',
    'Televendas', 'Não Informado']
Length: 6, dtype: str

In [39]:
dados.isnull().sum()

data_venda             550
mes                      0
cidade                   0
canal_venda              0
categoria                0
produto                  0
vendedor                 0
fidelidade_cliente       0
preco_unitario           0
custo_unitario           0
margem_pct              82
quantidade               0
desconto_pct             0
receita_total            0
frete                 1879
avaliacao_cliente     2955
prazo_entrega_dias    1504
devolucao                0
entrega_no_prazo         0
alta_temporada           0
flag_outlier_preco       0
dtype: int64

Explicação das decisões:

### C. Criação de novas colunas

### D. Filtros

### E. Agrupamentos com groupb

### F. Merge

### Conclusão

## Entregável 3 Seaborn

### A. Gráfico de barras

Interpretação do gráfico:

### B. Gráfico de linha

Interpretação do gráfico:

### C. Gráfico de dispersão

Interpretação do gráfico:

### D. Mapa de calor

Interpretação do gráfico:

### Conclusão